# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('asin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('review_average', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('brand', models.CharField(blank=True, max_length=256)),
                ('category', models.CharField(blank=True, max_length=256)),
                ('est_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('est_sales', models.IntegerField(blank=True, help_text='Predicted number of sales per month.', null=True)),
                ('sales_rank', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_tier', models.CharField(blank=True, max_length=128)),
                ('number_sellers', models.IntegerField(blank=True, null=True)),
                ('fba_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('seller', models.CharField(blank=True, max_length=128)),
                ('amz_store_code', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
