# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
        migrations.AddField(
            model_name='search',
            name='products',
            field=models.ManyToManyField(blank=True, to='amazon.Product'),
        ),
    ]
