# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_auto_20170321_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='jungle_scout_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='search',
            name='amz_store_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='search',
            name='amz_store_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='average_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='search',
            name='jungle_scout_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='search',
            name='search_volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
