# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_auto_20170331_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='super_search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amazon.SuperSearch'),
        ),
    ]
