# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_auto_20170331_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supersearch',
            options={'verbose_name_plural': 'Super Searches'},
        ),
        migrations.AddField(
            model_name='search',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
