# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_auto_20170405_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ('id',), 'verbose_name_plural': 'Searches'},
        ),
        migrations.AddField(
            model_name='search',
            name='product_list',
            field=models.TextField(blank=True),
        ),
    ]
