# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 15:00
from __future__ import unicode_literals

from django.db import migrations


def fill_product_list(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_auto_20170407_0859'),
    ]

    operations = [
        migrations.RunPython(fill_product_list)
    ]
