# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_auto_20170413_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsenode',
            name='follow',
            field=models.BooleanField(default=True),
        ),
    ]
