# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0014_search_browse_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supersearch',
            name='products',
        ),
        migrations.RemoveField(
            model_name='search',
            name='super_search',
        ),
        migrations.AddField(
            model_name='search',
            name='accessory_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='avg_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='first_page_space',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='max_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='max_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='min_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='seller_diversity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='trend',
            field=models.CharField(choices=[('upward', 'upward'), ('downward', 'downward'), ('stable', 'stable'), ('seasonal', 'seasonal'), ('unknown', 'unknown')], default='unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='search',
            name='category',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.DeleteModel(
            name='SuperSearch',
        ),
    ]
