# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0018_auto_20170510_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
