# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0020_auto_20170719_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsenode',
            name='top_level_node',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
