# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0021_browsenode_top_level_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='avg_review_score',
            field=models.FloatField(default=0),
        ),
    ]
