# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0022_search_avg_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproduct',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The unit cost you can acquire this product for.', max_digits=10),
        ),
    ]
