# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0023_favoriteproduct_unit_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='jungle_scout_id',
        ),
        migrations.RemoveField(
            model_name='search',
            name='jungle_scout_id',
        ),
    ]
