# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0025_auto_20170829_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='est_price',
        ),
    ]
