# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0026_remove_product_est_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amz_store_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_tier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='search',
            name='amz_store_code',
        ),
        migrations.RemoveField(
            model_name='search',
            name='amz_store_id',
        ),
        migrations.RemoveField(
            model_name='search',
            name='average_price',
        ),
        migrations.RemoveField(
            model_name='search',
            name='first_page_space',
        ),
        migrations.RemoveField(
            model_name='search',
            name='search_volume',
        ),
    ]
