# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0027_auto_20170829_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='product_list',
        ),
    ]
