# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0028_remove_search_product_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
