# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 15:23
from __future__ import unicode_literals

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170904_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='jaguaruser',
            name='password_reset_key',
            field=models.CharField(default=apps.users.models.randomize_key, max_length=8),
        ),
    ]
