# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 15:58
from __future__ import unicode_literals

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_jaguaruser_password_reset_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaguaruser',
            name='password_reset_key',
            field=models.CharField(default=apps.users.models.randomize_key, max_length=8, unique=True),
        ),
    ]
