#!C:\Users\SAMUEL~1\DOCUME~1\Work\JAGUAR~4\env\Scripts\python.exe
# Copyright 2014-2016, Damian Johnson and The Tor Project
# See LICENSE for licensing information

import stem.interpreter

if __name__ == '__main__':
  stem.interpreter.main()
